### PR TITLE
Add Region API URL as constant

### PR DESCRIPTION
**Pull request by NeilW**

### CODE REVIEW

**Comment by johnl** [comment]
Feels a bit like this should be a method to which you give the region code you want and it returns the url, since there will be future regions (and we have non-public regions). It could return gb1 as a default too, if we like?

Depends how you're using it I suppose.

**Comment by NeilW** [comment]
The lower interface I have is a map.

So if we refactored this into the client you would access `brightbox.RegionURL[brightbox.DefaultRegion]` to get the default.

Or via a variable. 

I'm using

```
mcnflag.StringFlag{
			EnvVar: "BRIGHTBOX_REGION",
			Name:   "brightbox-region",
			Usage:  "Brightbox Cloud Region",
			Value:  brightbox.defaultRegion,
		},
```

So it's down to whether we wrap these in functions - so you'd have

```
brightbox.ApiURL(brightbox.defaultRegion)
brightbox.TokenURL(brightbox.defaultRegion)
```

I don't like the idea of the empty string returning the default. I think in Go you need to be explicit since it doesn't have default parameters.

**Comment by johnl** [comment]
happy to provide a DefaultRegion constant for use like that yeah.

And I suppose we don't really need to return an error (unless we're going to validate the generated url first using a dns lookup, which I don't think is necessary) - it'll pop up as a dns lookup error later on anyway if someone uses an invalid zone.

**Comment by NeilW** [comment]
You need to return a lookup error if you use functions. So if I do 'ApiURL('jp1') I need a lookup error since strings have no 'nil' value. 

If you use a map, then the lookup error happens as part of the map reference call.

**Comment by NeilW** [comment]
I'm thinking

```Go
func ApiURL(regionCode string) (string, bool) {
}
func TokenURL(regionCode string) (string, bool) {
}
```

**Comment by johnl** [comment]
Seems a shame to have to ship a map of known region urls when they can be calculated from the region code, but I suppose it's do that, do a dns lookup, or don't support region codes and require full api urls.

Both the ruby and go cli require full api urls instead (though both have their own hardcoded default of api.gb1.brightbox.com (and the auth url defaults to whatever is provided as api url).

So let's just provide a DefaultRegionApiURL, containing the gb1 region auth url.

**Pull request merged**
